<a href="https://colab.research.google.com/github/Shreyasvaidya/Programming_problems/blob/main/linalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
v=np.random.randint(20,size=(3,3))
print(v)

[[ 9  6  5]
 [ 2 16  6]
 [ 5  4 12]]


In [ ]:
s=np.random.randint(20,size=(3,3))
v_sim=np.matmul(np.matmul(np.linalg.inv(s),v),s)
print(v_sim)

[[ -1.53191489 -10.89361702  -4.10638298]
 [ 45.70212766  45.65957447  40.84042553]
 [-12.63829787  -7.87234043  -7.12765957]]


In [ ]:
ev=np.linalg.eig(v)
print(ev)
es=np.linalg.eig(v_sim)
print(es)

(array([22.10473778,  6.13497173,  8.76029049]), array([[-0.51165206, -0.59967085,  0.01485241],
       [-0.6816657 , -0.32357894, -0.64046391],
       [-0.52301438,  0.73190952,  0.76784464]]))
(array([22.10473778,  8.76029049,  6.13497173]), array([[ 0.40766127, -0.74723357, -0.77327396],
       [-0.91052568,  0.59260553,  0.34326658],
       [ 0.06895854,  0.30076681,  0.53311859]]))


In [6]:
#magnitude of vector
n=int(input("Enter number of components"))
sum_vectors=0
for i in range(n):
  x=int(input("Enter component"))
  sum_vectors+=(x**2)

magnitude=sum_vectors**(1/2)
print(magnitude) 

Enter number of components4
Enter component-11423
Enter component8594
Enter component5961
Enter component5912
16577.907889718776
